{% set name = "brs_utils" %}
{% set version = "1.15.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/brs-utils/archive/refs/tags/{{ version }}.tar.gz
  sha256: 20251ddf6c04d926e29b4b6ddd2879dc968bc80501f79ee2af003aefdc12e8d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    - colorlog
    - colored

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - pytest-cov
  commands:
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/brs-utils
  summary: Generic Utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
