{% set name = "brs_utils" %}
{% set version = "1.26.0" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/brs-utils/archive/refs/tags/{{ version }}.tar.gz
  sha256: fd83d8fdaba3699d2ed46b46063c554d39df8912214ef4fbe376c9882fef229e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - colorlog
    - colored

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - pytest-cov
  commands:
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/brs-utils
  summary: Generic Utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
    - ramez17khaled
