{% set name = "brs_utils" %}
{% set version = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/brs-utils/archive/refs/tags/{{ version }}.tar.gz
  sha256: 95f27a33f57b461929bf9f4bcaf981d97f30fc4a3a82b0aa4a8c18cc0d14e9a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - colorlog
    - colored

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - pytest-cov
  commands:
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/brs-utils
  summary: "Generic Utilities"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
