{% set name = "brs_utils" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/brs-utils/archive/refs/tags/{{ version }}.tar.gz
  sha256: 14b8d54157aad0f90883550e157e82708dfb6cebacc3d0fb8c9370631d1ca41b

build:
  number: 0
  skip: true  # [py>=3.13]
  # noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - requests
    - colorlog
    - colored

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - pytest-cov
  commands:
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/brs-utils
  summary: Generic Utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
